# Generated by Django 3.2 on 2022-02-23 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroceryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_create', models.CharField(max_length=50)),
                ('create_item_date', models.DateTimeField(auto_now_add=True)),
                ('complete_item_date', models.DateTimeField(auto_now_add=True)),
                ('item_completed', models.BooleanField()),
            ],
        ),
    ]
