# Generated by Django 3.2 on 2022-02-25 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='url_shortner',
            new_name='UrlShortner',
        ),
    ]
