# Generated by Django 4.0.2 on 2022-02-25 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener', '0002_alter_link_url_click'),
    ]

    operations = [
        migrations.AlterField(
            model_name='click',
            name='language',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='click',
            name='referer',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='click',
            name='user_agent',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
