# Generated by Django 3.2 on 2022-02-25 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short', '0006_alter_shortcode_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortcode',
            name='code',
            field=models.CharField(max_length=200, verbose_name='short code'),
        ),
    ]
