# Generated by Django 4.0.2 on 2022-02-24 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('short_code', models.CharField(max_length=16)),
                ('url', models.CharField(max_length=200)),
            ],
        ),
    ]
