# Generated by Django 4.0.3 on 2022-03-24 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='capstone',
            field=models.URLField(),
        ),
    ]
