# Generated by Django 4.0.3 on 2022-03-24 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_capstone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='favorite_teacher',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='student',
            name='favorite_topic',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
