# Generated by Django 3.2 on 2022-02-24 22:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('short', '0002_auto_20220224_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortcode',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 24, 22, 44, 27, 737717, tzinfo=utc)),
        ),
    ]
