# Generated by Django 3.2 on 2022-02-25 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short', '0004_auto_20220225_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortcode',
            name='code',
            field=models.CharField(max_length=200, verbose_name='short code'),
        ),
        migrations.AlterField(
            model_name='shortcode',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created date'),
        ),
        migrations.AlterField(
            model_name='shortcode',
            name='url',
            field=models.URLField(verbose_name='long URL'),
        ),
        migrations.AlterField(
            model_name='shortcode',
            name='url_description',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='URL description'),
        ),
    ]
