# Generated by Django 4.0.2 on 2022-03-01 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GroceryItem',
            new_name='Url',
        ),
    ]
