# Generated by Django 4.0.2 on 2022-03-01 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener_app', '0002_rename_groceryitem_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='code',
        ),
        migrations.RemoveField(
            model_name='url',
            name='url',
        ),
        migrations.AddField(
            model_name='url',
            name='long_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='url',
            name='short_url',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
    ]
