# Generated by Django 4.0.3 on 2022-03-23 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['-first_name']},
        ),
    ]
