# Generated by Django 3.2 on 2022-03-24 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('cohort', models.CharField(max_length=200)),
                ('favorite_topic', models.CharField(max_length=200)),
                ('favorite_teacher', models.CharField(max_length=200)),
                ('capstone', models.URLField(verbose_name='capstone url')),
                ('students_app_url', models.URLField(blank=True, null=True, verbose_name='students url')),
            ],
        ),
    ]
