# Generated by Django 3.2 on 2022-03-02 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chirps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chirp',
            name='updated',
        ),
    ]
