# Generated by Django 3.2 on 2022-03-03 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chirps', '0002_remove_chirp_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chirp',
            options={'ordering': ['-created']},
        ),
    ]
