# Generated by Django 3.2 on 2022-03-03 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chirps', '0003_alter_chirp_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='chirp',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
