# Generated by Django 4.0.2 on 2022-03-03 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortened_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urlitem',
            name='description',
        ),
        migrations.AddField(
            model_name='urlitem',
            name='long_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='urlitem',
            name='short_url',
            field=models.CharField(max_length=6, null=True, unique=True),
        ),
    ]
