# Generated by Django 4.0.2 on 2022-03-01 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_author_id_post_message_post_parent_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discussion',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='author_id',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='discussion_id',
            new_name='discussion',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='parent_id',
            new_name='parent',
        ),
    ]
