# Generated by Django 3.2 on 2022-02-25 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urlshort',
            old_name='url_long',
            new_name='long_url',
        ),
        migrations.RemoveField(
            model_name='urlshort',
            name='url_short',
        ),
        migrations.AddField(
            model_name='urlshort',
            name='short_url',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
    ]
