# Generated by Django 3.2 on 2022-02-26 00:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener', '0002_auto_20220224_1836'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='urlshort',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='urlshort',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 25, 18, 34, 57, 582809)),
        ),
    ]
