# Generated by Django 4.0.3 on 2022-03-05 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glapp',
            name='completion',
            field=models.BooleanField(default=False),
        ),
    ]
