# Generated by Django 4.0.3 on 2022-03-05 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glapp', '0002_alter_glapp_completion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='glapp',
            old_name='desccription',
            new_name='description',
        ),
    ]
