# Generated by Django 3.2 on 2022-03-25 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='some_random_attribute',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
