# Generated by Django 4.0.3 on 2022-04-12 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chirpapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chirp',
            name='text',
            field=models.TextField(default='', max_length=200),
        ),
    ]
