# Generated by Django 4.0.3 on 2022-04-04 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='bio',
            new_name='bbio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
    ]
